### ISSUE TITLE
Visualization of final model

### ISSUE THREAD

**Issue by wangyiqing50** [saezlab/mistyR#25]
Since the final model is a linear combination of each view, I was wondering if it makes sense to visualize the final model and how.

For example, the importance which could be a weighted sum of each view by their contribution. In this case I don't care if they are colocalized or if they are neighbors. Just want to see which targets are spatially dependent with predictors.

**Comment by jtanevski** [comment]
When the importances are calculated the significance of the view contribution for that target is taken into account. You can choose to plot the heatmap per view without any cutoff or trim and you will get all predictor-target importances. All individual and unweighted importances are stored in the _importances_ element in the results list and the contributions are stored in the _contributions_ and the _contributions.stats_ elements. You can use them to aggregate the available information in any way you find useful. See the implementation of the function _collect_results_ , in particular the collection and aggregation of importances as an example. I think that the code starting at line 200 would be a good place to check. If i haven't answered your question, can you be a bit more specific please?
