### ISSUE TITLE
Run misty in subset regions of Visium for cell-colocalization analysis with deconvolution output  

### ISSUE THREAD

**Issue by lengfei5** [saezlab/mistyR#28]
Hi there, 

Appreciate this nice package and detailed documentation. 

Now I would like to do the cell-cololization analysis with the cell-type deconvolution output in Visium.
and I am mainly following the Vignette in https://saezlab.github.io/mistyR/articles/mistySeurat.html.

My question is if I can do this colocalization analysis using only some region of Visium data (i.e. injury or border regions, because our data is designed in the regeneration context).
My main concern is that the injury regions/border regions are quite small, 50-100 spots in Visium.
I am not sure they are many enough for the training in Misty.

Thank you.

**Comment by jtanevski** [comment]
Hi there. Thanks for using mistyR. Learning from 50-100 spots shouldn't be a problem, especially when using pipelines based on information from deconvolution of the spots. I would advise you to check if some of your variables have constant values or if they have a small number of unique values. I suggest removing constant variables and considering changing the default cv parameter to accommodate for variables with a small number of unique values.

**Comment by lengfei5** [comment]
Hi there, 

Many thanks for the prompt answer. I will try what you suggested.

Best,
