### ISSUE TITLE
Error in collect_results function

### ISSUE THREAD

**Issue by YaobangWang** [saezlab/mistyR#30]
Dear Professor:
I am very interested in the function of MISTy's spatial interaction analysis, after reading your article. However, when I tried to run MISTy with built-in data (data("synthetic")), the **collect_results** function encountered an error.
Everything runs normally, including the run_misty function, until the collect_results function. The following information appears here:

Collecting improvements
Error in mutate_cols(.data, ..., caller_env = caller_env()) : 
  Problem with `mutate()` column `gain.RMSE`.
i `gain.RMSE = 100 * (.data$intra.RMSE - .data$multi.RMSE)/.data$intra.RMSE`.
x Column `intra.RMSE` not found in `.data`.
Caused by error in `.data$intra.RMSE`:
! Column `intra.RMSE` not found in `.data`.

I checked the input data of the collect_results function, which is consistent with the sample data. I will be very grateful if you have any way to solve this problem and inform me.
Best regards
Wang

**Comment by jtanevski** [comment]
This is the same issue as #26 
The error is due to function deprecation in readr. This has now been resolved (23b3fdf) by requiring readr >= 2.0.0 in the Imports.
