### ISSUE TITLE
Issue with MistyR Heatmaps

### ISSUE THREAD

**Issue by deconvolute** [saezlab/mistyR#34]
I initially used MistyR with a dataset containing 9 cell types and found the results to be highly informative and useful. However, when I subsequently increased the number of cell types to 15 and reran MistyR, I noticed that the heatmaps generated appeared to be disoriented or misaligned.

I have ensured that the data preprocessing steps and input format remained consistent between the two runs, but I have not been able to resolve the issue on my own.

<img width="875" alt="image" src="https://github.com/saezlab/mistyR/assets/114025279/fd2d2b5c-9260-41fa-aea7-eb1440dd36e8">
<img width="883" alt="image" src="https://github.com/saezlab/mistyR/assets/114025279/37076863-9281-4996-9ea8-bf5e0634fdea">

**Comment by AteeqMKhaliq** [comment]
even I am facing the same issue, please let me know the solution, I hope the authors will respond soon!

**Comment by jtanevski** [comment]
Hi both. mistyR was affected by changes in dplyr >=1.1.0. We have already resolved this in mistyR v1.8.1. Can you please confirm that you have the latest version and you are still experiencing this issue?

**Comment by deconvolute** [comment]
Thanks for letting me know. It’s working perfectly fine after I updated it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jovan Tanevski ***@***.***>
Sent: Monday, October 9, 2023 6:03:17 AM
To: saezlab/mistyR ***@***.***>
Cc: Rajamohan, Meenakshi ***@***.***>; Author ***@***.***>
Subject: [External] Re: [saezlab/mistyR] Issue with MistyR Heatmaps (Issue #34)


This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Hi both. mistyR was affected by changes in dplyr >=1.1.0. We have already resolved this in mistyR v1.8.1. Can you please confirm that you have the latest version and you are still experiencing this issue?
