### ISSUE TITLE
Can I merge the results into one?

### ISSUE THREAD

**Issue by LynnChan99** [saezlab/mistyR#37]
Recently, I am trying to use misty to deconvolute near colocalization of mydata, but I could only use 1 slice once, if I want to analyze the final results together, can I just merge them together without any speical process? Thank you so much!

**Comment by jtanevski** [comment]
Run MISTy on one sample at a time as usual. Then you can simply collect and aggregate all results with `collect_results`  giving it a vector of paths at input as `misty.results <- collect_results(c("path/to/result1", "path/to/result2", "path/to/result3"))`. Note that `misty.results` now also contains statistics about all measures across all samples which will be reflected when plotting. If interested in different analyses, you can also access them directly.

**Comment by LynnChan99** [comment]
Thanks a lot for your reply. Besides, I am wondering what's the difference between juxta-view and para-view if I set the same radius to calculate? I can understand the juxta-view is based on the direct neigborhood cell-cell relationship and para-view is based on the tissue structure. But they are inferred in the same region, why the results will be so different? Thanks again!

**Comment by jtanevski** [comment]
Glad to be of help. For your question see the response here https://github.com/saezlab/mistyR/issues/35#issuecomment-1772958665
