### ISSUE TITLE
Question: IMC and single cell resolution ST data

### ISSUE THREAD

**Issue by spatts14** [saezlab/mistyR#43]
Hi! 

Really interested in trying to use MISTy for some IMC and single cell resolution spatial transcriptomics data. I saw in the paper that you analyzed very similar data types and you have those workflows in R. However, I am hoping to do this in python rather than R. 

I looked at the tutorial (https://liana-py.readthedocs.io/en/latest/notebooks/misty.html#Extract-Cell-type-Composition) and it used Visium data, so I wanted to see if there were any tutorials in python on the workflow/pipeline to analyze single cell resolution data?  
If not, would you be able to share with me how I can use MISTy to analyze IMC or Xenium ST data in Python?

Thanks!

**Comment by jtanevski** [comment]
Dear Sara

Apologies for not responding earlier, I unfortunately haven't seen the issue until now. In the meantime we updated the webpage to include more examples of pipelines for different scenarios. However, they are only in R at this time. The LIANA+ package has an implementation of MISTy that you can use. It shouldn't be difficult to adapt the vignettes from the page to work in LIANA+. If you have any difficulties please contact me directly via email (you can find it at the beginning of all vignettes) if you have more specific misty related questions or Daniel (daniel.dimitrov at uni-heidelberg.de) for LIANA+ specific questions.

Jovan

**Comment by huiyijiangling** [comment]
you mean we can modify the tutorial (https://liana-py.readthedocs.io/en/latest/notebooks/misty.html) use MISTy for some IMC and single cell resolution? Could you write a new tutorial for this?
