### ISSUE TITLE
Scaling before running linear model

### ISSUE THREAD

**Issue by Zach-Sten** [saezlab/mistyR#44]
Hello, 

I was reading through the methods for MISTy and wasn't sure if or how the factors in each view of the MISTy object are scaled before running the model. Could you provide some information on this? I am using the python version of MISTy within the Liana package.

**Comment by dbdimitrov** [comment]
Hi @Zach-Sten,

What do you mean by the factors in each view being scaled? 

In short, MISTy does not necessarily work with factors, but rather you can think of it as a series of leave-one-feature-out (LOFO) models - similar to GRN algorithms. Once these LOFO models are fit per target, we then use the predictions for each target in a subsequent model (typically ridge) to estimate the contribution of each view for each target. So, in that sense, it does not necessarily require scaling for the 'late-fusion' model.

Does this answer your question?

**Comment by Zach-Sten** [comment]
Apologies. What i meant to say was features not factors. My understanding now is that since it builds individual models for each view rather than combining the raw features from each view and then building a model. So therefore when its using the predictions from each LOFO they don't necessarily need to be scaled. Makes sense! Thanks for clarifying :)
