### ISSUE TITLE
Using MISTy on multiple samples

### ISSUE THREAD

**Issue by whitneyt1** [saezlab/mistyR#46]
Hello,

I'm interested in applying MISTy to 36 visium reactions across four timepoints. Do you have recommendations on how to implement MISTy to help identify spatially relevant features that may differ between clinical metadata? (timepoint, patients that recur etc). 

Should I set my intraview to these metadata? Or just subset my object and analyze each timepoint independently? 

Thanks!

**Comment by jtanevski** [comment]
I would suggest to first run MISTy with the same view composition on each sample independently. Afterwards you can collect and aggregate the results based on your criteria of interest, either for each time point or for each condition. In this manner MISTy will capture the most robust interactions per time point or condition.  The results of such aggregations of MISTy results  are directly comparable. You can either look at the individual results per time point or condition and interpret the results or use the [plot_contrast_results](https://saezlab.github.io/mistyR/reference/plot_contrast_results.html ) function to help you with the differences between two sets of results for a view of interest.

**Comment by whitneyt1** [comment]
Thank you so much!! @jtanevski
