### ISSUE TITLE
cutoff for Importance?

### ISSUE THREAD

**Issue by Li-ZhiD** [saezlab/mistyR#47]
Hi, nice tool! I want to know if the cutoff for importance needs to be positive and how to choose the threshold. 
For cell-cell colocalization, does a negative importance mean a bad relationship?

**Comment by jtanevski** [comment]
Technically the cutoff doesn't need to be positive, however a negative importance indicates a relationship for a particular predictor with below average importance when compared to all other predictors for the same target and view. 

I would suggest setting the cutoff at 1, or 0.5 if you want to highlight more potential relationships. Note that a cutoff of 1 will show only the relationships with an importance of 1 standard above the mean importance for that target. Lowering the cutoff threshold will result in highlighting more relationships while at the same time potentially introducing false positives. I wouldn't recommend in any case to set the cutoff below 0.

**Comment by Li-ZhiD** [comment]
Thank you！
