### ISSUE TITLE
parameters in functions add_juxtaview and add_paraview

### ISSUE THREAD

**Issue by zhumengyan** [saezlab/mistyR#48]
Thank you for developing this interesting software. I am trying to apply this software to my 10x Genomics Visium spatial transcriptomics data. 
While reviewing the tutorials and related articles, I noticed significant differences in the neighbor.thr parameter for add_juxtaview and the l parameter for add_paraview. For example, in "**Learning functional and structural spatial relationships with MISTy**," neighbor.thr and l are set to 130 and 200, respectively. However, in the article "**Spatial multi-omic map of human myocardial infarction**" the parameters for juxtaview and paraview are set to 5 and 15, respectively. 
Why is there such a large difference? It seems that one represents distance while the other represents the number of spots extended outward. Which way should I follow for setting these parameters?

**Comment by jtanevski** [comment]
The location information for each Visium spot can be represented in two different ways, as you have already noted, by the row and column location on the slide grid or by the pixel coordinates corresponding to the center of each spot. The l and the juxtaview threshold parameters in the two analyses are set to correspond to the representation used for the respective analysis - px in the first article and number of spots in the second. 

I would suggest working with pixel, or even better physical distance measures of location, i.e., pixel values scaled by the corresponding scale factor. While it isn't wrong to use the row and column information, you should be aware of the spatial configuration. On the Visium slide the spots are not actually arranged in a regular lattice, but are rather shifted in each consecutive row/column. The distance between the centers of two consecutive spots in a row is 100 microns while the distance between two consecutive spots in a column is around 70 microns (half of the size diagonal between spot s(i, j) and spot s(i+1, j+1).

**Comment by zhumengyan** [comment]
I understand, thank you.
